### ISSUE TITLE
Bad display on Edge / Firefox

### ISSUE THREAD

**Issue by slumbering** [toomuchdesign/react-minimal-pie-chart#73] opened 2019-09-02 14:03 UTC
When the Pie is animated, the drawing part is not properly display on Firefox and Edge.

![Screenshot_2019-09-02 Storybook](https://user-images.githubusercontent.com/1186424/64119904-2d96e700-cd9b-11e9-9663-fa4cb1425524.png)

### Specifications
- Version: 5.0.0
- Platforms: Firefox Quantum 68.0.2/Microsoft Edge 44.17763.1.0
- Subsystem: Windows 10

**Comment by toomuchdesign** [comment] 2019-09-02 20:50
Hi @slumbering , thank for reporting.
Do you confirm that there is no issue when animation is disabled?

**Comment by slumbering** [comment] 2019-09-03 11:51
I confirm that when animation is not enable the pie is correctly displayed. Thanks

**Comment by toomuchdesign** [comment] 2019-09-04 19:44
I still haven't had the possibility to test on Windows, but the only solution I see is to cleanup the properties responsible for the animation when this is completed. Which is maybe a good idea no matter the bug.

Here is [the PR](#76). Feel free to try it out and let me know.
Cheers!

**Comment by toomuchdesign** [comment] 2019-09-06 11:38
I can reproduce the issue on Windows 10/Edge but it doesn't seem to be related with animation (even though the animation blows up the visualisation).

I couldn't reproduce on Widows 10/Firefox 68, instead.

For Edge I don't see any possible fix: the browser doesn't accurately render svg path strokes nor `stroke-dasharray` style prop which are the foundation of `react-minimap-pie-chart` render strategy.

**Comment by toomuchdesign** [comment] 2020-02-14 15:05
I could reproduce on Safari for iPad, but only with `animation = false`. The `stroke-dasharray/offset` appended for animation seem to fix the render issue for this browser.

**Comment by toomuchdesign** [comment] 2020-02-15 20:11
Merged into #129

**Closed by toomuchdesign** 2020-02-15 20:11 UTC
Labels: bug
