### ISSUE TITLE
Import package with react-scripts-ts

### ISSUE THREAD

**Issue by andresmgot** [toomuchdesign/react-minimal-pie-chart#131] opened 2020-02-25 14:11 UTC
### Do you want to request a _feature_ or report a _bug_?

A _bug_?

### What is the current behaviour?

I am trying to render a PieChart component in a test, something like this:

```
import { mount } from "enzyme";
import * as React from "react";
import PieChart from "react-minimal-pie-chart";

it("renders a pie chart", () => {
  mount(<PieChart data={[{ value: 1, color: "blue" }]} />);
});
```

But when I try to execute it I get:

```
    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

I think the error is related to how the code is imported but I am not sure what could be the reason.

I am using `"typescript": "^3.7.2"` and ` "react-minimal-pie-chart": "^6.0.1"`.

### What is the expected behaviour?

To be able to render a PieChart using `jest`

### Steps to Reproduce the Problem

(Explained above, let me know if it's not reproducible)

Note that the code works as expected in the functional code, which is why I am confused.

**Comment by toomuchdesign** [comment] 2020-02-26 09:51
Hi @andresmgot,
It seems an issue related with your test environment or `enzyme` itself. May you try to reproduce the error on repl.it?

Cheers

**Comment by andresmgot** [comment] 2020-02-26 10:27
It could be, yes, but I am not sure what's the piece that's failing.

In this tarball I have added a minimal setup in which I can reproduce the issue:

[pie.tar.gz](https://github.com/toomuchdesign/react-minimal-pie-chart/files/4255022/pie.tar.gz)

If you run `yarn && npm run test` you should be able to reproduce it too.

**Comment by toomuchdesign** [comment] 2020-02-26 12:58
Someone else stumbled upon this issue in the past:
https://github.com/wmonk/create-react-app-typescript/issues/364

Importing the library like this should make friends again with TS.
```js
import * PieChart from "react-minimal-pie-chart";
```
I honestly don't know what's up with TS.

**Comment by andresmgot** [comment] 2020-02-26 14:58
I changed that (BTW, nit: `import * as PieChart from "react-minimal-pie-chart";`) and the funny thing is that the test now worked but the functional Typescript code failed to compile with:

```
JSX element type 'PieChart' does not have any construct or call signatures.
```

I think there is a problem with the TS definition. If I re-declare the module adding a file:

```
▶ cat src/react-minimal-pie-chart.d.ts 
declare module "react-minimal-pie-chart";
```

Both the test and the compilation works but I lose all the Typescript annotations.

**Comment by andresmgot** [comment] 2020-02-26 15:34
Nevermind, redefining the package bypassed the validation but the application failed in the browser anyway so I cannot import the package with `import * as PieChart`

**Comment by toomuchdesign** [comment] 2020-02-26 15:50
Got it. Happy to support if you find something wrong coming from this repo.

**Comment by andresmgot** [comment] 2020-02-26 16:28
I have been trying different formats for declaring the types for typescript but none seemed to work in all scenarios :man_shrugging: 

Leaving this in case someone has more knowledge about Typescript.

Thanks for replying!

**Comment by toomuchdesign** [comment] 2020-04-13 13:33
Closing since it seems a `react-scripts-ts` issue.

**Closed by toomuchdesign** 2020-04-13 13:33 UTC
