### ISSUE TITLE
Prop type for Chart enforces optional props

### ISSUE THREAD

**Issue by mkarajohn** [toomuchdesign/react-minimal-pie-chart#168] opened 2020-05-11 20:31 UTC
### Do you want to request a _feature_ or report a _bug_?
Bug

### What is the current behaviour?
Omitting optional props throws warnings in the IDE

### What is the expected behaviour?
To not throw any warnings if I omit optional props

### Steps to Reproduce the Problem
Create any Chart component and omit any of the props defined [here](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/master/src/Chart/Chart.tsx#L51) 

The change to the props was introduced in [this](https://github.com/toomuchdesign/react-minimal-pie-chart/commit/24ed725117689865eebf3555f0050e00cd6a7b72#diff-e1c5fc57f81f5c6e27e5e0e57c1ed561R67) commit and effectively makes these props required.

### Specifications

- Version: 8.0.0

It would be my pleasure to open a PR in order to fix this

![image](https://user-images.githubusercontent.com/3789226/81608821-88c7b180-93df-11ea-9496-b9b9fe03bbe2.png)

**Comment by toomuchdesign** [comment] 2020-05-11 21:16
Hi @mkarajohn,
thanks for reporting!

This could be related to the way we join props and defaultProps types. Let's find out.

I'm quite concerned about the fact that [tests](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/master/src/__tests__/types.tsx) haven't caught the issue.

**Comment by mkarajohn** [comment] 2020-05-11 22:37
Hi, 

>This could be related to the way we join props and defaultProps types. Let's find out.

Yes, it seems to me as well, this is the cause.

the intersection in [this](https://github.com/toomuchdesign/react-minimal-pie-chart/commit/24ed725117689865eebf3555f0050e00cd6a7b72#diff-e1c5fc57f81f5c6e27e5e0e57c1ed561R67) line makes the `defaultProps` required

You can see [this](https://www.typescriptlang.org/play/index.html?ssl=16&ssc=12&pln=8&pc=1#code/C4TwDgpgBA9mwEsYDsCGAbAzlAvFA3gLABQUZUqA-AFxTICuAtgEYQBOA3CeVMzXU1acSAXxIlQkKGwgBHeghkATXAW7lUtBi3ZdiY4hPDQEyYO0wQAxuZV44iFBmwAyaXIXK9JAGb1kNkjIUH7IABSobADmmLSm5myWNhBKAJRqpOQywPRswZExega+-mH4zLQAjCKpQA) TS sandbox example, for the same effect

**Comment by toomuchdesign** [comment] 2020-05-12 08:35
I thought about it for a moment.

From the library's perspective [`PropsWithDefaults`](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/9a112ad31b64e214aec6d500e5635d9f20603983/src/Chart/Chart.tsx#L65) describes the `props` object (with default props) expected by [`PieChart`](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/9a112ad31b64e214aec6d500e5635d9f20603983/src/Chart/Chart.tsx#L67) function component.

Default props are therefore marked as required because they are expected to be provided or defaulted by React. In my [usual TS+React routine](https://codesandbox.io/s/rmpc-typings-xe3f8?file=/src/App.tsx) I can't get any typing error.

And `PropsWithDefaults` is what you get when you retrieve components' props with:
```ts
React.ComponentProps<typeof PieChart>
```

Since pure [`Props` types](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/9a112ad31b64e214aec6d500e5635d9f20603983/src/Chart/Chart.tsx#L14) alone are not exported, there's currently no way to retrieve the type definition of the props the user is expected to provide. Which is probably a quite common issue with React's defaultProps in TS.

I'm totally open to find a better typing setup.

BTW, can I see a repro of your typing error? Maybe you're using the library in a way I haven't taken into account.

Cheers! 🙌

**Comment by mkarajohn** [comment] 2020-05-12 10:43
My setup is WebStorm 2019.3.4 on Mac and Windows 10. I get the warning regardless of OS.

I am using the component like this
```
<PieChart
              key={'proper'}
              animate
              animationDuration={500}
              animationEasing="ease-out"
              background={'#bfbfbf'}
              css={chartStyles}
              lineWidth={60}
              data={chartData}
            />
```

I cannot disclose any more code than that.

>Default props are therefore marked as required because they are expected to be provided or defaulted by React.

I don't think default props should be marked as required. On that regard, my IDE is right for throwing those warnings at me. 

Think about it. Default props are optional props, in the end. Whether or not your component handles them with some default value is an implementation detail. To the user they should not be any different from any other optional props, during development time. The docs exist for that reason, so that we can tell what props are defaulted with what values. 

If I alter the definition in the `Chart.d.ts` file to `export declare function PieChart(props: Props): JSX.Element;` the Typescript gods are appeased. 

Cheers!

**Comment by toomuchdesign** [comment] 2020-05-12 15:10
Hi @mkarajohn,
crazy idea: could the issue be related to WebStorm?! I took a look to it's [bug tracker](https://youtrack.jetbrains.com/issues?q=defaultProps) and found a few reports that seem to be similar to what you described.

**Comment by mkarajohn** [comment] 2020-05-12 17:04
Not a crazy idea at all :D. It may be one of these issues, However i am not sure which one could it be. The [1st](https://youtrack.jetbrains.com/issue/WEB-36612) one in that list (which is very similar to this case) is closed as a duplicate of [this](https://youtrack.jetbrains.com/issue/WEB-33517) which is supposed to be fixed. I don't know, honestly, proceed with this issue however you feel like.

**Comment by toomuchdesign** [comment] 2020-05-12 17:47
In the meanwhile I found that the React team decided to [deprecate `defaultProps` for function component](https://github.com/reactjs/rfcs/pull/107). 😱 

In the next future we might consider getting rid of them and switch to JS default arguments even though this would mess up the code quite a bit.

**Comment by mkarajohn** [comment] 2020-05-12 18:29
>In the meanwhile I found that the React team decided to deprecate defaultProps for function component. 😱

Yep, that's true. For the better, if you ask me

**Comment by toomuchdesign** [comment] 2020-05-12 20:41
Added an entry to docs' todo.

Please feel free to reopen in case the bug doesn't come from WebStorm.

**Closed by toomuchdesign** 2020-05-12 20:41 UTC

**Comment by mkarajohn** [comment] 2020-12-21 20:39
Hi, it's this time of the year again :smile: 

Well, I upgraded to TS 4.1.3 from 3.9.7 and I got this exact same error again. I actually had completely forgotten about this issue, until now, when I searched for it and got here again :sweat_smile: 

This time I am on Linux. 
A quick search at JetBrain's issue tracker brought [nothing](https://youtrack.jetbrains.com/issues?q=typescript%204%20defaultprops%20webstorm)

Still the only fix for me is to do `export declare function PieChart(props: Props): JSX.Element;`

```
// global.d.ts

declare module 'react-minimal-pie-chart' {
  declare type Props = {
    animate?: boolean;
    animationDuration?: number;
    animationEasing?: string;
    background?: string;
    center?: [number, number];
    children?: ReactNode;
    className?: string;
    data: Data;
    lengthAngle?: number;
    lineWidth?: number;
    label?: LabelRenderFunction;
    labelPosition?: number;
    labelStyle?: CSSProperties | ((dataIndex: number) => CSSProperties | undefined);
    onBlur?: EventHandler<FocusEvent>;
    onClick?: EventHandler<MouseEvent>;
    onFocus?: EventHandler<FocusEvent>;
    onKeyDown?: EventHandler<KeyboardEvent>;
    onMouseOut?: EventHandler<MouseEvent>;
    onMouseOver?: EventHandler<MouseEvent>;
    paddingAngle?: number;
    radius?: number;
    reveal?: number;
    rounded?: boolean;
    segmentsShift?: number | ((dataIndex: number) => number | undefined);
    segmentsStyle?: CSSProperties | ((dataIndex: number) => CSSProperties | undefined);
    segmentsTabIndex?: number;
    startAngle?: number;
    style?: CSSProperties;
    totalValue?: number;
    viewBoxSize?: [number, number];
  };

  declare function PieChart(props: Props): JSX.Element;
}
```
I still think my response [here](https://github.com/toomuchdesign/react-minimal-pie-chart/issues/168#issuecomment-627262959) has some base.

Cheers

**Comment by toomuchdesign** [comment] 2020-12-22 10:42
Hi @mkarajohn,
I can't say for sure it's JetBrain. From a maintainer perspective I'd be inclined to take Typescript as a source of truth. If TS doesn't complain then it's fine.

User facing types are [tested here](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/master/src/__tests__/types.tsx) and executed with bare `tsc` [from here](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/master/package.json#L25). Would it be possible to reproduce the error outside the IDE?

As a next step we could get rid of React's `defaultProps` (respecting size constraints of this library), but it's not on my top priority right now :) Happy to help out if you wanted to try a PR.

**Comment by mkarajohn** [comment] 2020-12-22 11:25
Well, it does in fact throw when simply running `tsc`

```bash
$ yarn tsc
yarn run v1.22.5
$ /mnt/4E141ED6141EC13F//Workspace//node_modules/.bin/tsc
src/pages/IssuesPage/subpages/Conflicts/components/Chart/Chart.tsx:155:12 - error TS2740: Type '{ key: string; background: string; css: SerializedStyles; lineWidth: number; data: never[]; }' is missing the following properties from type '{ animationDuration: number; animationEasing: string; center: [number, number]; data: Data; labelPosition: number; lengthAngle: number; lineWidth: number; paddingAngle: number; radius: number; startAngle: number; viewBoxSize: [...]; }': animationDuration, animationEasing, center, labelPosition, and 5 more.

155           <PieChart
               ~~~~~~~~

src/pages/IssuesPage/subpages/Conflicts/components/Chart/Chart.tsx:166:14 - error TS2740: Type '{ key: string; animate: true; animationDuration: number; animationEasing: string; background: string; css: SerializedStyles; lineWidth: number; data: ChartNormalizedData[]; }' is missing the following properties from type '{ animationDuration: number; animationEasing: string; center: [number, number]; data: Data; labelPosition: number; lengthAngle: number; lineWidth: number; paddingAngle: number; radius: number; startAngle: number; viewBoxSize: [...]; }': center, labelPosition, lengthAngle, paddingAngle, and 3 more.

166             <PieChart
                 ~~~~~~~~


Found 2 errors.
```

I tried replicating here but I couldn't. https://codesandbox.io/s/optimistic-voice-mxfvs?file=/src/App.tsx

Honestly, I am not sure what is happening. For me it makes sense that it is throwing (wth the union of the `Props` and `DefaultProps` ) but if I cannot reproduce it in another environment, what can I say :sweat_smile:

**Comment by toomuchdesign** [comment] 2020-12-22 12:20
2 brief questions:

- Can you build your app?
- Is there a way to replicate the issue out of your machine?

**Comment by mkarajohn** [comment] 2020-12-22 13:17
>Can you build your app?

No, the compiling process throws, since this is a TS error

>Is there a way to replicate the issue out of your machine?

I tried in the codesanbox, above, but I cannot reproduce

> What's your IDE and which version?

On linux:
WebStorm 2020.3
Build #WS-203.5981.135, built on November 27, 2020

On Mac:
WebStorm 2020.2.4
Build #WS-202.8194.6, built on November 24, 2020 

BTW, this i how my IDE sees the type when I hover over the component

```typescript
export function PieChart(     props: Props & {animationDuration: number, animationEasing: string, center: [number, number], data: Data, labelPosition: number, lengthAngle: number, lineWidth: number, paddingAngle: number, radius: number, startAngle: number, viewBoxSize: [number, number]}):    JSX.Element
```

**Comment by toomuchdesign** [comment] 2020-12-22 13:34
Do you maybe build through your IDE? I've just built the chart in a CRA with TS and no errors whatsoever.

**Comment by mkarajohn** [comment] 2020-12-22 13:49
> Do you maybe build through your IDE? I've just built the chart in a CRA with TS and no errors whatsoever.

I build from within the IDE, yes, but the `tsc` command whose output I posted above was executed from a standalone terminal, outside of the IDE.

Like I said, I am just as confused, but since I have found a workaround, I am not really requesting for a fix :)

**Comment by toomuchdesign** [comment] 2020-12-22 14:19
Just one last thing: would you mind pasting here your `tsconfig.json` file?

**Comment by mkarajohn** [comment] 2020-12-22 14:21
Sure, I don't mind even if it's not the last thing :smile: 

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "baseUrl": "./src",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "downlevelIteration": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
```

The codesandbox from above uses the basic configurations I use on my machine

**Comment by TimMensch** [comment] 2021-10-05 15:34
I found this thread when looking for a solution to this exact problem.

So the workaround is to override the TypeScript types? Seems broken. At least this issue should be re-opened. 

I'm on TypeScript 4.1.2. Would _really_ appreciate a fix for this. My workaround for now is to `@ts-ignore` your type signature, which is hardly any good when the objective is to _increase_ the strictness of the types everywhere.
